name: pub_admin
description: "Prest Zone - Premium vending machines with digital advertising."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.8.0
  firebase_storage: ^12.3.6
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.3
  file_picker: ^8.1.4
  video_player: ^2.9.3
  go_router: ^14.8.0
  url_launcher: ^6.3.1
  flutter_staggered_animations: ^1.1.1
  google_fonts: ^6.2.1
  webview_flutter: ^4.10.0
  webview_flutter_web: ^0.2.3+4
  flutter_animate: ^4.5.2
  visibility_detector: ^0.4.0+2
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/prest-zone-logo-removebg.png
    - assets/instagram.png
    - assets/facebook.png
    - assets/website.png
    - assets/machine1.png
    - assets/machine2.png
    - assets/machine3.png
    - assets/machine4.png
    - assets/machine5.png
    - assets/machine6.png
    - assets/machine7.png
    - assets/fatales.png
    - assets/mahparis.png
    - assets/arena_location.png
    - assets/digits.jpg
    - assets/arenagym.jpg
    - assets/zebraclub.jpg
